# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 02:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='ano',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900)]),
        ),
    ]
